"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.emailError = () => 'Invalid email';
exports.requiredError = () => 'Required';
exports.minLengthError = (length) => `Minimum length should be ${length}`;
exports.hasAnUpperError = () => 'Should have an uppercase';
exports.hasALowerError = () => 'Should have a lowercase';
exports.hasADigitError = () => 'Should have a digit';
exports.isSameError = () => 'Does not match';
exports.isAlphaError = () => 'Should be alphabets';
exports.isAlphaNumericError = () => 'Should be alpha-numeric';
exports.isNumericError = () => 'Should be numeric';
exports.isLengthError = (length) => `Length should be ${length}`;
exports.isDecimalError = () => 'Should be decimal';
